<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\Mahasiswa $model
 */
$copyParams = $model->attributes;

$this->title = "Detail ".Yii::t('app', 'Mahasiswa');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Mahasiswas'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->nama_lengkap, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud mahasiswa-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>
    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a(
                '<span class="fa fa-pencil"></span> ' . 'Edit',
                ['update', 'id' => $model->id],
                ['class' => 'btn btn-info']) ?>

            <?= Html::a(
                '<span class="fa fa-plus"></span> ' . 'New',
                ['create'],
                ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">
            <?= Html::a('<span class="fa fa-list"></span> '
                . 'Full list', ['index'], ['class' => 'btn btn-default']) ?>
        </div>

    </div>
    <br clear="all">

    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Detail </h3>
        </div>

        <div class="box-body">
            <?php $this->beginBlock('app\models\Mahasiswa'); ?>

            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    [
                        'label'=>'Foto',
                        'format'=>'raw',
                        'value'=>Html::img("../uploads/mahasiswa/foto/".$model->foto,['class'=>'img','width'=>'150','height'=>'auto']),
                    ],
                    'nama_lengkap',
                    'nimrn',
                    'tempat_lahir',
                    'tanggal_lahir',
                    'alamat',
                    'tahun_masuk',
                    'status',

// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
                    [
                        'format' => 'html',
                        'attribute' => 'fakultas',
                        'value' => ($model->getFakultas0()->one() ? Html::a($model->getFakultas0()->one()->nama_fakultas, ['fakultas/view', 'id' => $model->getFakultas0()->one()->id,]) : '<span class="label label-warning">?</span>'),
                    ],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
                    [
                        'format' => 'html',
                        'attribute' => 'jurusan',
                        'value' => ($model->getJurusan0()->one() ? Html::a($model->getJurusan0()->one()->nama_jurusan, ['jurusan/view', 'id' => $model->getJurusan0()->one()->id,]) : '<span class="label label-warning">?</span>'),
                    ],
                ],
            ]); ?>


            <hr/>

            <?= Html::a('<span class="fa fa-trash"></span> ' . 'Delete', ['delete', 'id' => $model->id],
                [
                    'class' => 'btn btn-danger',
                    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
                    'data-method' => 'post',
                ]); ?>
            <?php $this->endBlock(); ?>



            <?= Tabs::widget(
                [
                    'id' => 'relation-tabs',
                    'encodeLabels' => false,
                    'items' => [[
                        'label' => '<b class=""># ' . $model->id . '</b>',
                        'content' => $this->blocks['app\models\Mahasiswa'],
                        'active' => true,
                    ],]
                ]
            );
            ?>        </div>

    </div>


</div>
