<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
 * @var yii\web\View $this
 * @var app\models\MataKuliah $model
 * @var yii\widgets\ActiveForm $form
 */

?>

<div class="mata-kuliah-form">

    <?php $form = ActiveForm::begin([
            'id' => 'MataKuliah',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-error',
            'options' => ['enctype' => 'multipart/form-data'],
        ]
    );
    ?>

    <div class="clearfix"></div>
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Form</h3>
        </div>

        <div class="box-body">

            <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
            $form->field($model, 'id_jurusan')->dropDownList(
                \yii\helpers\ArrayHelper::map(app\models\Jurusan::find()->all(), 'id', 'nama_jurusan'),
                ['prompt' => 'Pilih Jurusan']
            ); ?>
            <?= $form->field($model, 'mata_kuliah')->textInput(['maxlength' => true]) ?>
            <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
            $form->field($model, 'semester')->dropDownList(
                \yii\helpers\ArrayHelper::map(app\models\Semester::find()->all(), 'semester', 'semester'),
                ['prompt' => 'Pilih semester']
            ); ?>
        </div>

        <div class="box-footer">
            <?php echo $form->errorSummary($model); ?>

            <?= Html::submitButton(
                '<span class="fa fa-check"></span> ' .
                ($model->isNewRecord ? 'Create' : 'Save'),
                [
                    'id' => 'save-' . $model->formName(),
                    'class' => 'btn btn-success'
                ]
            );
            ?>
        </div>

    </div>
    <?php ActiveForm::end(); ?>

</div>

