<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "index_nilai".
 *
 * @property integer $id
 * @property string $index_nilai
 * @property string $aliasModel
 */
abstract class IndexNilai extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'index_nilai';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['index_nilai'], 'required'],
            [['index_nilai'], 'string', 'max' => 10]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'index_nilai' => 'Index Nilai',
        ];
    }




}
