<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "jurusan".
 *
 * @property integer $id
 * @property integer $fakultas
 * @property string $nama_jurusan
 *
 * @property \app\models\Fakultas $fakultas0
 * @property \app\models\Mahasiswa[] $mahasiswas
 * @property \app\models\MataKuliah[] $mataKuliahs
 * @property string $aliasModel
 */
abstract class Jurusan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'jurusan';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fakultas', 'nama_jurusan'], 'required'],
            [['fakultas'], 'integer'],
            [['nama_jurusan'], 'string', 'max' => 100],
            [['fakultas'], 'exist', 'skipOnError' => true, 'targetClass' => Fakultas::className(), 'targetAttribute' => ['fakultas' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'fakultas' => 'Fakultas',
            'nama_jurusan' => 'Nama Jurusan',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFakultas0()
    {
        return $this->hasOne(\app\models\Fakultas::className(), ['id' => 'fakultas']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMahasiswas()
    {
        return $this->hasMany(\app\models\Mahasiswa::className(), ['jurusan' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMataKuliahs()
    {
        return $this->hasMany(\app\models\MataKuliah::className(), ['id_jurusan' => 'id']);
    }




}
