<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "mahasiswa".
 *
 * @property integer $id
 * @property string $nama_lengkap
 * @property string $nimrn
 * @property string $tempat_lahir
 * @property string $tanggal_lahir
 * @property string $alamat
 * @property string $tahun_masuk
 * @property integer $status
 * @property string $foto
 * @property integer $fakultas
 * @property integer $jurusan
 *
 * @property \app\models\Jurusan $jurusan0
 * @property \app\models\Fakultas $fakultas0
 * @property string $aliasModel
 */
abstract class Mahasiswa extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'mahasiswa';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama_lengkap', 'nimrn', 'tempat_lahir', 'tanggal_lahir', 'alamat', 'tahun_masuk', 'status', 'fakultas', 'jurusan'], 'required'],
            [[ 'fakultas', 'jurusan'], 'integer'],
            [['nama_lengkap', 'nimrn', 'tempat_lahir', 'tanggal_lahir', 'alamat'], 'string', 'max' => 100],
            [['tahun_masuk'], 'string', 'max' => 4],
            [['status'],'string'],
            [['foto'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['jurusan'], 'exist', 'skipOnError' => true, 'targetClass' => Jurusan::className(), 'targetAttribute' => ['jurusan' => 'id']],
            [['fakultas'], 'exist', 'skipOnError' => true, 'targetClass' => Fakultas::className(), 'targetAttribute' => ['fakultas' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama_lengkap' => 'Nama Lengkap',
            'nimrn' => 'NIMRN',
            'tempat_lahir' => 'Tempat Lahir',
            'tanggal_lahir' => 'Tanggal Lahir',
            'alamat' => 'Alamat',
            'tahun_masuk' => 'Tahun Masuk',
            'status' => 'Status',
            'foto' => 'Foto',
            'fakultas' => 'Fakultas',
            'jurusan' => 'Jurusan',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJurusan0()
    {
        return $this->hasOne(\app\models\Jurusan::className(), ['id' => 'jurusan']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFakultas0()
    {
        return $this->hasOne(\app\models\Fakultas::className(), ['id' => 'fakultas']);
    }


    public function upload()
    {
        if ($this->validate()) {
            $this->foto->saveAs('uploads/mahasiswa/foto/' . time() . '.' . $this->foto->extension);
            return true;
        } else {
            return false;
        }
    }

}
