<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "nilai".
 *
 * @property integer $id
 * @property integer $mahasiswa
 * @property integer $mata_kuliah
 * @property string $nilai
 * @property string $index
 * @property integer $semester
 *
 * @property \app\models\MataKuliah $mataKuliah
 * @property \app\models\Mahasiswa $mahasiswa0
 * @property string $aliasModel
 */
abstract class Nilai extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'nilai';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['mahasiswa', 'mata_kuliah', 'nilai', 'index', 'semester'], 'required'],
            [['mahasiswa', 'mata_kuliah','jurusan',], 'integer'],
            [['nilai'], 'string', 'max' => 5],
            [['semester'],'string'],
            [['index'], 'string', 'max' => 4],
            [['mata_kuliah'], 'exist', 'skipOnError' => true, 'targetClass' => MataKuliah::className(), 'targetAttribute' => ['mata_kuliah' => 'id']],
            [['mahasiswa'], 'exist', 'skipOnError' => true, 'targetClass' => Mahasiswa::className(), 'targetAttribute' => ['mahasiswa' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mahasiswa' => 'Mahasiswa',
            'mata_kuliah' => 'Mata Kuliah',
            'nilai' => 'Nilai',
            'index' => 'Index',
            'semester' => 'Semester',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMataKuliah()
    {
        return $this->hasOne(\app\models\MataKuliah::className(), ['id' => 'mata_kuliah']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMahasiswa0()
    {
        return $this->hasOne(\app\models\Mahasiswa::className(), ['id' => 'mahasiswa']);
    }




}
