<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "semester".
 *
 * @property integer $id
 * @property string $semester
 * @property string $aliasModel
 */
abstract class Semester extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'semester';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['semester'], 'required'],
            [['semester'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'semester' => 'Semester',
        ];
    }




}
