<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
 * @var yii\web\View $this
 * @var app\models\Nilai $model
 * @var yii\widgets\ActiveForm $form
 */

?>

<div class="nilai-form">

    <?php $form = ActiveForm::begin([
            'id' => 'Nilai',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-error',
            'options' => ['enctype' => 'multipart/form-data'],
        ]
    );
    ?>

    <div class="clearfix"></div>
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Form</h3>
        </div>

        <div class="box-body">
            <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
            $form->field($model, 'mahasiswa')->widget(kartik\select2\Select2::className(), [
                'data' => \yii\helpers\ArrayHelper::map(app\models\Mahasiswa::find()->all(), 'id', 'nimrn'),
                'options' => ['placeholder' => 'Pilih NIMRN'],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]); ?>
            <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
            $form->field($model, 'jurusan')->dropDownList(
                ArrayHelper::map(\app\models\Jurusan::find()->all(),"id",'nama_jurusan'),
                ['prompt'=>'Jurusan']
            ); ?>
            <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
            $form->field($model, 'mata_kuliah')->widget(kartik\select2\Select2::className(),[
                'data' => \yii\helpers\ArrayHelper::map(app\models\MataKuliah::find()->all(), 'id', 'mata_kuliah'),
                'options' => ['placeholder' => 'Pilih Mata Kuliah'],
                'pluginOptions' => [
                'allowClear' => true
            ],
            ]); ?>
            <?= $form->field($model, 'nilai')->textInput(['maxlength' => true]) ?>
            <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
            $form->field($model, 'index')->dropDownList(
                ArrayHelper::map(\app\models\IndexNilai::find()->all(),"index_nilai",'index_nilai'),
                ['prompt'=>'Index Nilai']
            ); ?>

            <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
            $form->field($model, 'semester')->dropDownList(
                ArrayHelper::map(\app\models\Semester::find()->all(),"semester",'semester'),
                ['prompt'=>'Semester']
            ); ?>
        </div>

        <div class="box-footer">
            <?php echo $form->errorSummary($model); ?>

            <?= Html::submitButton(
                '<span class="fa fa-check"></span> ' .
                ($model->isNewRecord ? 'Create' : 'Save'),
                [
                    'id' => 'save-' . $model->formName(),
                    'class' => 'btn btn-success'
                ]
            );
            ?>
        </div>

    </div>
    <?php ActiveForm::end(); ?>

</div>

