<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\Nilai $model
 */
$copyParams = $model->attributes;

$this->title = Yii::t('app', 'Nilai');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Nilais'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud nilai-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>
    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a(
                '<span class="fa fa-pencil"></span> ' . 'Edit',
                ['update', 'id' => $model->id],
                ['class' => 'btn btn-info']) ?>

            <?= Html::a(
                '<span class="fa fa-plus"></span> ' . 'New',
                ['create'],
                ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">
            <?= Html::a('<span class="fa fa-list"></span> '
                . 'Full list', ['index'], ['class' => 'btn btn-default']) ?>
        </div>

    </div>
    <br clear="all">

    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Detail </h3>
        </div>

        <div class="box-body">
            <?php $this->beginBlock('app\models\Nilai'); ?>


            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
                    [
                        'format' => 'html',
                        'label' => 'NIMRN',
                        'value' => ($model->getMahasiswa0()->one() ? Html::a($model->getMahasiswa0()->one()->nimrn, ['mahasiswa/view', 'id' => $model->getMahasiswa0()->one()->id,]) : '<span class="label label-warning">?</span>'),
                    ],
                    [
                        'format' => 'html',
                        'label' => 'Nama Mahasiswa',
                        'value' => ($model->getMahasiswa0()->one() ? Html::a($model->getMahasiswa0()->one()->nama_lengkap, ['mahasiswa/view', 'id' => $model->getMahasiswa0()->one()->id,]) : '<span class="label label-warning">?</span>'),
                    ],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
                    [
                        'format' => 'html',
                        'attribute' => 'mata_kuliah',
                        'value' => ($model->getMataKuliah()->one() ? Html::a($model->getMataKuliah()->one()->mata_kuliah, ['mata-kuliah/view', 'id' => $model->getMataKuliah()->one()->id,]) : '<span class="label label-warning">?</span>'),
                    ],
                    'nilai',
                    'index',
                    'semester',
                    [
                        'attribute'=>'jurusan',
                        'label'=>'Jurusan',
                        'format'=>'raw',
                        'value'=>"<b>".\app\models\Jurusan::findOne($model->jurusan)->nama_jurusan."</b>",
                    ]
                ],
            ]); ?>


            <hr/>

            <?= Html::a('<span class="fa fa-trash"></span> ' . 'Delete', ['delete', 'id' => $model->id],
                [
                    'class' => 'btn btn-danger',
                    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
                    'data-method' => 'post',
                ]); ?>
            <?php $this->endBlock(); ?>



            <?= Tabs::widget(
                [
                    'id' => 'relation-tabs',
                    'encodeLabels' => false,
                    'items' => [[
                        'label' => '<b class=""># ' . $model->id . '</b>',
                        'content' => $this->blocks['app\models\Nilai'],
                        'active' => true,
                    ],]
                ]
            );
            ?>        </div>

    </div>


</div>
